import { SchoolProfile, Subject, LearningObjective, MaterialScope, Student, Teacher, ClassRoom } from '../types/raport';

export const defaultClasses: ClassRoom[] = [
  {
    id: 'class-7a',
    name: 'VII-A',
    level: 'VII',
    phase: 'D',
    academicYear: '2023/2024',
    waliKelasId: 'teacher-1',
    waliKelasName: 'Imat Rohimat, S.Pd., M.Kom.',
    waliKelasNip: '198507202010011015',
    roomName: 'Ruang 7A',
  },
  {
    id: 'class-7b',
    name: 'VII-B',
    level: 'VII',
    phase: 'D',
    academicYear: '2023/2024',
    waliKelasId: 'teacher-2',
    waliKelasName: 'Dra. Maria L. Sumampouw, M.Pd.',
    waliKelasNip: '196805121993032004',
    roomName: 'Ruang 7B',
  },
  {
    id: 'class-8a',
    name: 'VIII-A',
    level: 'VIII',
    phase: 'D',
    academicYear: '2023/2024',
    waliKelasId: 'teacher-3',
    waliKelasName: 'Jefry Rumagit, S.Pd.',
    waliKelasNip: '198904152014021002',
    roomName: 'Ruang 8A',
  },
  {
    id: 'class-9a',
    name: 'IX-A',
    level: 'IX',
    phase: 'D',
    academicYear: '2023/2024',
    waliKelasId: '',
    waliKelasName: 'Siti Rahmah, S.Pd.I.',
    waliKelasNip: '199203112019032014',
    roomName: 'Ruang 9A',
  },
];

export const defaultTeachers: Teacher[] = [
  {
    id: 'teacher-1',
    name: 'Imat Rohimat, S.Pd., M.Kom.',
    nip: '198507202010011015',
    email: 'imat75@guru.smp.belajar.id',
    role: 'wali_kelas',
    assignedClass: 'VII-A',
    isWaliKelas: true,
  },
  {
    id: 'teacher-2',
    name: 'Dra. Maria L. Sumampouw, M.Pd.',
    nip: '196805121993032004',
    email: 'maria.sumampouw@guru.smp.belajar.id',
    role: 'wali_kelas',
    assignedClass: 'VII-B',
    isWaliKelas: true,
  },
  {
    id: 'teacher-3',
    name: 'Jefry Rumagit, S.Pd.',
    nip: '198904152014021002',
    email: 'jefry.rumagit@guru.smp.belajar.id',
    role: 'wali_kelas',
    assignedClass: 'VIII-A',
    isWaliKelas: true,
  },
  {
    id: 'teacher-4',
    name: 'Siti Rahmah, S.Pd.I.',
    nip: '199203112019032014',
    email: 'siti.rahmah@guru.smp.belajar.id',
    role: 'guru_mapel',
    assignedClass: 'Semua',
    subjectId: 'agama',
    isWaliKelas: false,
  },
];

export const initialSchoolProfile: SchoolProfile = {
  namaSekolah: 'SMP MEFENG',
  npsn: '60203264',
  nss: '201270205001',
  alamatSekolah: 'JL. POROS NO.1 TRANS SP 2 LALUBI',
  kodePos: '97728',
  desaKelurahan: 'LALUBI',
  kecamatan: 'GANE TIMUR',
  kabupatenKota: 'HALMAHERA SELATAN',
  provinsi: 'MALUKU UTARA',
  website: 'smpmefeng.sch.id',
  email: 'smpmefeng@gmail.com',
  namaKepalaSekolah: 'Dra. Maria L. Sumampouw, M.Pd.',
  nipKepalaSekolah: '196805121993032004',
  namaGuruKelas: 'Imat Rohimat, S.Pd., M.Kom.',
  nipGuruKelas: '198507202010011015',
  kelas: 'VII-A',
  fase: 'D',
  semester: '2 (Dua / Genap)',
  semesterAngka: 2,
  tahunPelajaran: '2023/2024',
  tempatTanggalRapor: 'Lalubi, 21 Juni 2024',
  tempatRapor: 'Lalubi',
  tanggalRapor: '21 Juni 2024',
  schoolName: 'SMP MEFENG',
  grade: 'VII-A',
  phase: 'D',
  academicYear: '2023/2024',
  teacherName: 'Imat Rohimat, S.Pd., M.Kom.',
  teacherNip: '198507202010011015',
  principalName: 'Dra. Maria L. Sumampouw, M.Pd.',
  principalNip: '196805121993032004',
  headmasterName: 'Dra. Maria L. Sumampouw, M.Pd.',
  headmasterNip: '196805121993032004',
  schoolAddress: 'JL. POROS NO.1 TRANS SP 2 LALUBI',
  schoolCity: 'HALMAHERA SELATAN',
  schoolSubdistrict: 'GANE TIMUR',
  schoolVillage: 'LALUBI',
  schoolProvince: 'MALUKU UTARA',
  schoolPostalCode: '97728',
  schoolPhone: '-',
  schoolWebsite: 'smpmefeng.sch.id',
  schoolEmail: 'smpmefeng@gmail.com',
  reportDate: '21 Juni 2024',
  reportPlace: 'Lalubi',
};

export const defaultSchoolConfig = initialSchoolProfile;

export const defaultSubjects: Subject[] = [
  { id: 'agama', code: 'PAI/PAK', name: 'Pendidikan Agama dan Budi Pekerti', category: 'wajib' },
  { id: 'pancasila', code: 'PPKn', name: 'Pendidikan Pancasila', category: 'wajib' },
  { id: 'bindonesia', code: 'BIN', name: 'Bahasa Indonesia', category: 'wajib' },
  { id: 'matematika', code: 'MAT', name: 'Matematika', category: 'wajib' },
  { id: 'ipa', code: 'IPA', name: 'Ilmu Pengetahuan Alam (IPA)', category: 'wajib' },
  { id: 'ips', code: 'IPS', name: 'Ilmu Pengetahuan Sosial (IPS)', category: 'wajib' },
  { id: 'binggris', code: 'BIG', name: 'Bahasa Inggris', category: 'wajib' },
  { id: 'pjok', code: 'PJK', name: 'PJOK', category: 'wajib' },
  { id: 'seni', code: 'SBK', name: 'Seni dan Prakarya', category: 'wajib' },
  { id: 'informatika', code: 'INF', name: 'Informatika', category: 'wajib' },
  { id: 'mulok1', code: 'ML1', name: 'Muatan Lokal 1 (Bahasa Daerah)', category: 'mulok' },
  { id: 'mulok2', code: 'ML2', name: 'Muatan Lokal 2 (Kearifan Lokal)', category: 'mulok' },
];

export const defaultLearningObjectives: LearningObjective[] = [
  // Agama Kristen
  { id: 'tp-ag-1', subjectId: 'agama', tpNumber: 1, tpCode: 'TP 1', description: 'Memahami karya penyelamatan Allah dalam Yesus Kristus bagi manusia berdosa', religionTarget: 'Kristen' },
  { id: 'tp-ag-2', subjectId: 'agama', tpNumber: 2, tpCode: 'TP 2', description: 'Menjelaskan makna hidup baru sebagai wujud pertobatan dan pembaruan hidup', religionTarget: 'Kristen' },
  { id: 'tp-ag-3', subjectId: 'agama', tpNumber: 3, tpCode: 'TP 3', description: 'Menerapkan teladan kerendahan hati Yesus Kristus dalam relasi dengan sesama', religionTarget: 'Kristen' },
  { id: 'tp-ag-4', subjectId: 'agama', tpNumber: 4, tpCode: 'TP 4', description: 'Memahami peran Roh Kudus dalam membimbing dan menguatkan orang percaya', religionTarget: 'Kristen' },
  { id: 'tp-ag-5', subjectId: 'agama', tpNumber: 5, tpCode: 'TP 5', description: 'Mewujudkan rasa syukur atas pemeliharaan Allah dalam kehidupan sehari-hari', religionTarget: 'Kristen' },
  
  // Agama Islam
  { id: 'tp-ag-6', subjectId: 'agama', tpNumber: 1, tpCode: 'TP 1', description: 'Memahami makna beriman kepada Allah SWT melalui Asmaul Husna (Al-Alim, Al-Khabir, As-Sami, Al-Bashir)', religionTarget: 'Islam' },
  { id: 'tp-ag-7', subjectId: 'agama', tpNumber: 2, tpCode: 'TP 2', description: 'Menerapkan tata cara salat berjemaah dan zikir setelah salat dengan tertib', religionTarget: 'Islam' },
  { id: 'tp-ag-8', subjectId: 'agama', tpNumber: 3, tpCode: 'TP 3', description: 'Meneladani sifat mulia Rasulullah SAW dalam kehidupan bermasyarakat', religionTarget: 'Islam' },
  { id: 'tp-ag-9', subjectId: 'agama', tpNumber: 4, tpCode: 'TP 4', description: 'Membaca dan menghafal QS. An-Nisa ayat 59 dan QS. An-Nahl ayat 64 dengan tartil', religionTarget: 'Islam' },
  { id: 'tp-ag-10', subjectId: 'agama', tpNumber: 5, tpCode: 'TP 5', description: 'Menerapkan perilaku jujur, amanah, dan istiqamah dalam keseharian', religionTarget: 'Islam' },

  // Pendidikan Pancasila
  { id: 'tp-ppkn-1', subjectId: 'pancasila', tpNumber: 1, tpCode: 'TP 1', description: 'Menganalisis sejarah kelahiran dan perumusan Pancasila sebagai dasar negara' },
  { id: 'tp-ppkn-2', subjectId: 'pancasila', tpNumber: 2, tpCode: 'TP 2', description: 'Menerapkan nilai-nilai luhur Pancasila dalam interaksi di lingkungan sekolah dan masyarakat' },
  { id: 'tp-ppkn-3', subjectId: 'pancasila', tpNumber: 3, tpCode: 'TP 3', description: 'Mengidentifikasi norma dan aturan yang berlaku dalam kehidupan bermasyarakat' },
  { id: 'tp-ppkn-4', subjectId: 'pancasila', tpNumber: 4, tpCode: 'TP 4', description: 'Menunjukkan komitmen terhadap penegakan hak dan kewajiban warga negara' },
  { id: 'tp-ppkn-5', subjectId: 'pancasila', tpNumber: 5, tpCode: 'TP 5', description: 'Menghargai keberagaman suku, agama, ras, dan antargolongan dalam bingkai Bhinneka Tunggal Ika' },

  // Bahasa Indonesia
  { id: 'tp-bind-1', subjectId: 'bindonesia', tpNumber: 1, tpCode: 'TP 1', description: 'Mengidentifikasi informasi penting dan struktur teks deskripsi yang dibaca dan didengar' },
  { id: 'tp-bind-2', subjectId: 'bindonesia', tpNumber: 2, tpCode: 'TP 2', description: 'Menyajikan gagasan dan kesan kreatif dalam bentuk teks puisi dan cerita fantasi' },
  { id: 'tp-bind-3', subjectId: 'bindonesia', tpNumber: 3, tpCode: 'TP 3', description: 'Menganalisis unsur kebahasaan dan struktur penulisan teks prosedur praktis' },
  { id: 'tp-bind-4', subjectId: 'bindonesia', tpNumber: 4, tpCode: 'TP 4', description: 'Menulis teks berita dan laporan hasil observasi dengan kaidah ejaan yang tepat' },
  { id: 'tp-bind-5', subjectId: 'bindonesia', tpNumber: 5, tpCode: 'TP 5', description: 'Mengkritisi pesan dan nilai moral dalam karya sastra cerita rakyat dan fabel' },

  // Matematika
  { id: 'tp-mat-1', subjectId: 'matematika', tpNumber: 1, tpCode: 'TP 1', description: 'Mengoperasikan bilangan bulat dan pecahan dalam pemecahan masalah kontekstual' },
  { id: 'tp-mat-2', subjectId: 'matematika', tpNumber: 2, tpCode: 'TP 2', description: 'Menyelesaikan bentuk aljabar linear satu variabel dan pertidaksamaan linear' },
  { id: 'tp-mat-3', subjectId: 'matematika', tpNumber: 3, tpCode: 'TP 3', description: 'Menerapkan konsep perbandingan senilai dan berbalik nilai dalam situasi nyata' },
  { id: 'tp-mat-4', subjectId: 'matematika', tpNumber: 4, tpCode: 'TP 4', description: 'Menghitung keliling dan luas bangun datar segiempat dan segitiga secara presisi' },
  { id: 'tp-mat-5', subjectId: 'matematika', tpNumber: 5, tpCode: 'TP 5', description: 'Menyajikan dan menafsirkan data dalam bentuk diagram batang, garis, dan lingkaran' },

  // IPA
  { id: 'tp-ipa-1', subjectId: 'ipa', tpNumber: 1, tpCode: 'TP 1', description: 'Memahami metode ilmiah, pengukuran, dan besaran satuan dalam penyelidikan sains' },
  { id: 'tp-ipa-2', subjectId: 'ipa', tpNumber: 2, tpCode: 'TP 2', description: 'Mengidentifikasi sifat zat, perubahan wujud benda, dan pemisahan campuran sederhana' },
  { id: 'tp-ipa-3', subjectId: 'ipa', tpNumber: 3, tpCode: 'TP 3', description: 'Menganalisis konsep suhu, kalor, pemuaian, dan perpindahan kalor dalam kehidupan' },
  { id: 'tp-ipa-4', subjectId: 'ipa', tpNumber: 4, tpCode: 'TP 4', description: 'Menjelaskan interaksi makhluk hidup dengan lingkungan serta dinamika ekosistem' },
  { id: 'tp-ipa-5', subjectId: 'ipa', tpNumber: 5, tpCode: 'TP 5', description: 'Memahami struktur lapisan bumi, mitigasi bencana gempa bumi, dan sistem tata surya' },

  // IPS
  { id: 'tp-ips-1', subjectId: 'ips', tpNumber: 1, tpCode: 'TP 1', description: 'Memahami konsep ruang dan konektivitas antarruang di kepulauan Indonesia' },
  { id: 'tp-ips-2', subjectId: 'ips', tpNumber: 2, tpCode: 'TP 2', description: 'Menganalisis interaksi sosial dan pengaruh lembaga sosial terhadap pembentukan karakter' },
  { id: 'tp-ips-3', subjectId: 'ips', tpNumber: 3, tpCode: 'TP 3', description: 'Menjelaskan peran pelaku ekonomi dalam memenuhi kebutuhan masyarakat' },
  { id: 'tp-ips-4', subjectId: 'ips', tpNumber: 4, tpCode: 'TP 4', description: 'Menelusuri jejak peradaban masa praaksara dan masuknya kerajaan Hindu-Buddha-Islam' },
  { id: 'tp-ips-5', subjectId: 'ips', tpNumber: 5, tpCode: 'TP 5', description: 'Mengidentifikasi potensi sumber daya alam maritim dan strategi pelestariannya' },

  // Bahasa Inggris
  { id: 'tp-bing-1', subjectId: 'binggris', tpNumber: 1, tpCode: 'TP 1', description: 'Mengidentifikasi ungkapan sapaan, pamitan, terima kasih, dan meminta maaf dalam interaksi interpersonal' },
  { id: 'tp-bing-2', subjectId: 'binggris', tpNumber: 2, tpCode: 'TP 2', description: 'Menyusun teks lisan dan tulis sederhana untuk menyatakan jati diri dan hubungan keluarga' },
  { id: 'tp-bing-3', subjectId: 'binggris', tpNumber: 3, tpCode: 'TP 3', description: 'Menggunakan ungkapan memberi dan meminta informasi terkait hari, waktu, tanggal, dan tahun' },
  { id: 'tp-bing-4', subjectId: 'binggris', tpNumber: 4, tpCode: 'TP 4', description: 'Mendeskripsikan benda, hewan, dan tempat umum di sekitar sekolah (Descriptive text)' },
  { id: 'tp-bing-5', subjectId: 'binggris', tpNumber: 5, tpCode: 'TP 5', description: 'Menafsirkan makna lirik lagu dan pesan inspiratif pendek berbahasa Inggris' },

  // PJOK
  { id: 'tp-pjok-1', subjectId: 'pjok', tpNumber: 1, tpCode: 'TP 1', description: 'Mempraktikkan variasi gerak spesifik permainan bola besar (Sepak Bola, Bola Voli, Bola Basket)' },
  { id: 'tp-pjok-2', subjectId: 'pjok', tpNumber: 2, tpCode: 'TP 2', description: 'Mempraktikkan gerak dasar atletik lari jarak pendek, lompat jauh, dan tolak peluru' },
  { id: 'tp-pjok-3', subjectId: 'pjok', tpNumber: 3, tpCode: 'TP 3', description: 'Mempraktikkan jurus dasar pencak silat dan teknik pembelaan diri' },
  { id: 'tp-pjok-4', subjectId: 'pjok', tpNumber: 4, tpCode: 'TP 4', description: 'Melakukan latihan kebugaran jasmani terkait kesehatan (daya tahan, kekuatan, kelenturan)' },
  { id: 'tp-pjok-5', subjectId: 'pjok', tpNumber: 5, tpCode: 'TP 5', description: 'Menerapkan pola hidup sehat dan pencegahan bahaya pergaulan bebas serta zat adiktif' },

  // Seni & Prakarya
  { id: 'tp-seni-1', subjectId: 'seni', tpNumber: 1, tpCode: 'TP 1', description: 'Menggambar gubahan ragam hias fauna, flora, dan geometris pada media kertas/kanvas' },
  { id: 'tp-seni-2', subjectId: 'seni', tpNumber: 2, tpCode: 'TP 2', description: 'Menerapkan prinsip komposisi, proporsi, dan perspektif dalam menggambar bentuk alam benda' },
  { id: 'tp-seni-3', subjectId: 'seni', tpNumber: 3, tpCode: 'TP 3', description: 'Menciptakan karya kerajinan tangan dari bahan limbah lunak organik dan anorganik' },
  { id: 'tp-seni-4', subjectId: 'seni', tpNumber: 4, tpCode: 'TP 4', description: 'Menyanyikan lagu daerah Minahasa/Sulawesi Utara dengan teknik pernapasan dan artikulasi baik' },
  { id: 'tp-seni-5', subjectId: 'seni', tpNumber: 5, tpCode: 'TP 5', description: 'Mempraktikkan gerak tari tradisional kreasi dengan iringan musik ritmis' },

  // Informatika
  { id: 'tp-inf-1', subjectId: 'informatika', tpNumber: 1, tpCode: 'TP 1', description: 'Menerapkan berpikir komputasional untuk menyelesaikan persoalan komputasi secara efisien' },
  { id: 'tp-inf-2', subjectId: 'informatika', tpNumber: 2, tpCode: 'TP 2', description: 'Menjelaskan antarmuka pengguna berbasis grafis dan struktur sistem operasi' },
  { id: 'tp-inf-3', subjectId: 'informatika', tpNumber: 3, tpCode: 'TP 3', description: 'Mengelola folder dan berkas dokumen digital secara rapi dan terstruktur' },
  { id: 'tp-inf-4', subjectId: 'informatika', tpNumber: 4, tpCode: 'TP 4', description: 'Membuat dan mengirimkan surel serta memanfaatkan media kolaborasi daring secara etis' },
  { id: 'tp-inf-5', subjectId: 'informatika', tpNumber: 5, tpCode: 'TP 5', description: 'Membuat brosur informatif dan dokumen terpadu menggunakan aplikasi pengolah kata' },
  { id: 'tp-inf-6', subjectId: 'informatika', tpNumber: 6, tpCode: 'TP 6', description: 'Membuat slide presentasi yang komunikatif dengan animasi dan transisi yang tepat' },
  { id: 'tp-inf-7', subjectId: 'informatika', tpNumber: 7, tpCode: 'TP 7', description: 'Mengidentifikasi perangkat keras komputer berdasarkan fungsi input, proses, dan output' },
  { id: 'tp-inf-8', subjectId: 'informatika', tpNumber: 8, tpCode: 'TP 8', description: 'Menjelaskan ragam perangkat lunak aplikasi, sistem, dan utilitas pendukung komputasi' },
  { id: 'tp-inf-9', subjectId: 'informatika', tpNumber: 9, tpCode: 'TP 9', description: 'Memahami komunikasi data dan interaksi antardevice melalui Bluetooth dan Wi-Fi' },
  { id: 'tp-inf-10', subjectId: 'informatika', tpNumber: 10, tpCode: 'TP 10', description: 'Menghubungkan peranti komputer ke jaringan internet dan memahami keamanan siber dasar' },
];

export const defaultMaterialScopes: MaterialScope[] = [
  { id: 'lm-ag-1', subjectId: 'agama', lmNumber: 1, lmCode: 'LM 1', title: 'Karya Penyelamatan & Iman' },
  { id: 'lm-ag-2', subjectId: 'agama', lmNumber: 2, lmCode: 'LM 2', title: 'Keteladanan Hidup Baru & Roh Kudus' },
  { id: 'lm-ppkn-1', subjectId: 'pancasila', lmNumber: 1, lmCode: 'LM 1', title: 'Kelahiran & Nilai Pancasila' },
  { id: 'lm-ppkn-2', subjectId: 'pancasila', lmNumber: 2, lmCode: 'LM 2', title: 'Norma Hukum & Hak Kewajiban' },
  { id: 'lm-bind-1', subjectId: 'bindonesia', lmNumber: 1, lmCode: 'LM 1', title: 'Teks Deskripsi & Puisi' },
  { id: 'lm-bind-2', subjectId: 'bindonesia', lmNumber: 2, lmCode: 'LM 2', title: 'Teks Prosedur & Laporan Hasil Observasi' },
  { id: 'lm-mat-1', subjectId: 'matematika', lmNumber: 1, lmCode: 'LM 1', title: 'Bilangan Bulat, Pecahan & Aljabar' },
  { id: 'lm-mat-2', subjectId: 'matematika', lmNumber: 2, lmCode: 'LM 2', title: 'Perbandingan, Geometri & Data Statistik' },
  { id: 'lm-ipa-1', subjectId: 'ipa', lmNumber: 1, lmCode: 'LM 1', title: 'Metode Ilmiah, Zat & Kalor' },
  { id: 'lm-ipa-2', subjectId: 'ipa', lmNumber: 2, lmCode: 'LM 2', title: 'Ekosistem, Lapisan Bumi & Tata Surya' },
  { id: 'lm-ips-1', subjectId: 'ips', lmNumber: 1, lmCode: 'LM 1', title: 'Konektivitas Keruangan & Interaksi Sosial' },
  { id: 'lm-ips-2', subjectId: 'ips', lmNumber: 2, lmCode: 'LM 2', title: 'Aktivitas Ekonomi & Sejarah Kepulauan' },
  { id: 'lm-bing-1', subjectId: 'binggris', lmNumber: 1, lmCode: 'LM 1', title: 'Greetings & Personal Information' },
  { id: 'lm-bing-2', subjectId: 'binggris', lmNumber: 2, lmCode: 'LM 2', title: 'Describing Things & Time Expressions' },
  { id: 'lm-pjok-1', subjectId: 'pjok', lmNumber: 1, lmCode: 'LM 1', title: 'Permainan Bola Besar & Atletik' },
  { id: 'lm-pjok-2', subjectId: 'pjok', lmNumber: 2, lmCode: 'LM 2', title: 'Bela Diri & Kebugaran Jasmani' },
  { id: 'lm-seni-1', subjectId: 'seni', lmNumber: 1, lmCode: 'LM 1', title: 'Ragam Hias & Gambar Bentuk' },
  { id: 'lm-seni-2', subjectId: 'seni', lmNumber: 2, lmCode: 'LM 2', title: 'Kerajinan Limbah & Musik Tradisi' },
  { id: 'lm-inf-1', subjectId: 'informatika', lmNumber: 1, lmCode: 'LM 1', title: 'Berpikir Komputasional & TIK' },
  { id: 'lm-inf-2', subjectId: 'informatika', lmNumber: 2, lmCode: 'LM 2', title: 'Sistem Komputer & Jaringan Internet' },
];

export const sampleStudents: Student[] = [
  {
    id: 'std-1',
    noUrut: 1,
    nis: '232407001',
    nisn: '0104589211',
    name: 'Albar Jonathan Walangare',
    gender: 'L',
    birthPlace: 'Manado',
    birthDate: '2011-04-14',
    religion: 'Kristen',
    familyStatus: 'Anak Kandung',
    childOrder: 1,
    prevSchool: 'SD Negeri 06 Manado',
    studentAddress: 'Jl. Sam Ratulangi No. 45',
    studentVillage: 'Wenang Selatan',
    studentDistrict: 'Wenang',
    studentPhone: '081244556677',
    acceptedClass: 'VII (Tujuh)',
    acceptedDate: '15 Juli 2023',
    parentFather: 'David Walangare',
    parentMother: 'Grace Rondonuwu',
    jobFather: 'Wiraswasta',
    jobMother: 'Guru',
    parentAddressRoad: 'Jl. Sam Ratulangi No. 45',
    parentAddressVillage: 'Wenang Selatan',
    parentAddressDistrict: 'Wenang',
    parentAddressCity: 'Manado',
    parentAddressProvince: 'Sulawesi Utara',
    parentPhone: '081244556677',
    guardianName: '-',
    guardianJob: '-',
    guardianAddress: '-',
    guardianPhone: '-',
    phone: '081244556677',
    heightS1: 152,
    heightS2: 154,
    weightS1: 44,
    weightS2: 46,
    healthHearing: 'Baik',
    healthVision: 'Normal',
    healthTeeth: 'Bersih / Sehat',
    achievementArt: 'Juara 2 Lomba Vokal Solo Tingkat Kota',
    achievementSport: 'Anggota Tim Futsal Sekolah',
    attendanceSakit: 0,
    attendanceIzin: 1,
    attendanceAlpa: 0,
    ekskul1Name: 'Pramuka',
    ekskul1Grade: 'Sangat Berkembang',
    ekskul1Desc: 'Sangat cakap dalam baris-berbaris, teknik tali temali, kepemimpinan regu, dan sandi morse.',
    ekskul2Name: 'Palang Merah Remaja (PMR)',
    ekskul2Grade: 'Berkembang',
    ekskul2Desc: 'Aktif dan tanggap dalam simulasi pertolongan pertama pada kecelakaan.',
    teacherNotes: 'Albar menunjukkan antusiasme belajar yang luar biasa, berkarakter santun, dan mampu memimpin kelompok dengan baik.',
    decision: 'Naik Kelas',
    decisionTargetClass: 'VIII-A',
  },
  {
    id: 'std-2',
    noUrut: 2,
    nis: '232407002',
    nisn: '0105678122',
    name: 'Amanda Felicia Pangemanan',
    gender: 'P',
    birthPlace: 'Tomohon',
    birthDate: '2011-06-22',
    religion: 'Kristen',
    prevSchool: 'SD GMIM Tomohon',
    studentAddress: 'Jl. Babe Palar No. 18, Manado',
    parentFather: 'Hendrik Pangemanan',
    parentMother: 'Novita Lumempouw',
    jobFather: 'PNS',
    jobMother: 'Dokter',
    parentAddressRoad: 'Jl. Babe Palar No. 18',
    parentAddressVillage: 'Rike',
    parentAddressDistrict: 'Wanea',
    parentAddressCity: 'Manado',
    parentAddressProvince: 'Sulawesi Utara',
    phone: '081388990011',
    heightS1: 150,
    heightS2: 151,
    weightS1: 42,
    weightS2: 43,
    healthHearing: 'Baik',
    healthVision: 'Normal',
    healthTeeth: 'Sehat',
    achievementScience: 'Juara 1 Olimpiade Sains Nasional (OSN) IPA Tingkat Kota',
    attendanceSakit: 0,
    attendanceIzin: 0,
    attendanceAlpa: 0,
    ekskul1Name: 'Pramuka',
    ekskul1Grade: 'Sangat Berkembang',
    ekskul1Desc: 'Sangat aktif dalam kegiatan perkemahan sabtu-minggu dan bakti sosial.',
    ekskul2Name: 'Klub Sains',
    ekskul2Grade: 'Sangat Berkembang',
    ekskul2Desc: 'Mampu melakukan penelitian ilmiah sederhana berbasis lingkungan hidup.',
    teacherNotes: 'Prestasi akademik Amanda sangat cemerlang, teliti dalam mengerjakan tugas, dan santun terhadap sesama.',
    decision: 'Naik Kelas',
    decisionTargetClass: 'VIII-A',
  },
  {
    id: 'std-3',
    noUrut: 3,
    nis: '232407003',
    nisn: '0112345678',
    name: 'Bryan Timothy Sondakh',
    gender: 'L',
    birthPlace: 'Manado',
    birthDate: '2011-08-05',
    religion: 'Kristen',
    prevSchool: 'SD Katolik Santa Theresia',
    studentAddress: 'Jl. Boulevard No. 88, Manado',
    parentFather: 'Ronald Sondakh',
    parentMother: 'Irene Wowor',
    jobFather: 'Karyawan Swasta',
    jobMother: 'Ibu Rumah Tangga',
    parentAddressRoad: 'Jl. Boulevard No. 88',
    parentAddressVillage: 'Sario Tumpaan',
    parentAddressDistrict: 'Sario',
    parentAddressCity: 'Manado',
    parentAddressProvince: 'Sulawesi Utara',
    phone: '081122334455',
    attendanceSakit: 1,
    attendanceIzin: 0,
    attendanceAlpa: 0,
    ekskul1Name: 'Pramuka',
    ekskul1Grade: 'Berkembang',
    ekskul1Desc: 'Disiplin dan bertanggung jawab terhadap tugas kepramukaan.',
    teacherNotes: 'Bryan memiliki bakat di bidang matematika dan informatika. Terus tingkatkan keaktifan diskusi di kelas.',
    decision: 'Naik Kelas',
    decisionTargetClass: 'VIII-A',
  },
  {
    id: 'std-4',
    noUrut: 4,
    nis: '232407004',
    nisn: '0108992341',
    name: 'Clarissa Michelle Rumondor',
    gender: 'P',
    birthPlace: 'Minahasa Utara',
    birthDate: '2011-03-19',
    religion: 'Katolik',
    prevSchool: 'SD Don Bosco Manado',
    studentAddress: 'Jl. Pumorow No. 12, Manado',
    parentFather: 'Stefanus Rumondor',
    parentMother: 'Theresia Polii',
    jobFather: 'Wiraswasta',
    jobMother: 'Akuntan',
    parentAddressRoad: 'Jl. Pumorow No. 12',
    parentAddressVillage: 'Banjer',
    parentAddressDistrict: 'Tikala',
    parentAddressCity: 'Manado',
    parentAddressProvince: 'Sulawesi Utara',
    phone: '081344552211',
    attendanceSakit: 0,
    attendanceIzin: 0,
    attendanceAlpa: 0,
    ekskul1Name: 'Pramuka',
    ekskul1Grade: 'Sangat Berkembang',
    ekskul1Desc: 'Menunjukkan inisiatif tinggi dalam kegiatan kelompok dan kepedulian lingkungan.',
    ekskul2Name: 'Paduan Suara',
    ekskul2Grade: 'Sangat Berkembang',
    ekskul2Desc: 'Memiliki musikalitas tinggi dan vokal sopran yang jernih.',
    teacherNotes: 'Clarissa adalah siswa berprestasi, ramah, dan menjadi teladan bagi teman sekelasnya.',
    decision: 'Naik Kelas',
    decisionTargetClass: 'VIII-A',
  },
  {
    id: 'std-5',
    noUrut: 5,
    nis: '232407005',
    nisn: '0115566778',
    name: 'Danendra Al-Ghifari Prasetyo',
    gender: 'L',
    birthPlace: 'Kotamobagu',
    birthDate: '2011-09-12',
    religion: 'Islam',
    prevSchool: 'SD Islam Terpadu Manado',
    studentAddress: 'Jl. Hasanuddin No. 34, Manado',
    parentFather: 'Bambang Prasetyo',
    parentMother: 'Siti Rahmawati',
    jobFather: 'TNI-AD',
    jobMother: 'PNS',
    parentAddressRoad: 'Jl. Hasanuddin No. 34',
    parentAddressVillage: 'Sindulang',
    parentAddressDistrict: 'Tuminting',
    parentAddressCity: 'Manado',
    parentAddressProvince: 'Sulawesi Utara',
    phone: '081299887766',
    attendanceSakit: 0,
    attendanceIzin: 0,
    attendanceAlpa: 1,
    ekskul1Name: 'Pramuka',
    ekskul1Grade: 'Berkembang',
    ekskul1Desc: 'Menguasai keterampilan dasar pioneering dan sandi ambalan.',
    ekskul2Name: 'Pencak Silat',
    ekskul2Grade: 'Sangat Berkembang',
    ekskul2Desc: 'Menguasai jurus tunggal baku dan memiliki stamina fisik prima.',
    teacherNotes: 'Danendra memiliki ketangkasan olahraga yang istimewa. Pertahankan kedisiplinan dan semangat belajar.',
    decision: 'Naik Kelas',
    decisionTargetClass: 'VIII-A',
  },
  {
    id: 'std-6',
    noUrut: 6,
    nis: '232407006',
    nisn: '0106677889',
    name: 'Elvira Nathania Manoppo',
    gender: 'P',
    birthPlace: 'Manado',
    birthDate: '2011-05-30',
    religion: 'Kristen',
    prevSchool: 'SD Eben Haezar Manado',
    studentAddress: 'Jl. Bethesda No. 25, Manado',
    parentFather: 'Alex Manoppo',
    parentMother: 'Meyke Paat',
    jobFather: 'Advokat',
    jobMother: 'Wiraswasta',
    parentAddressRoad: 'Jl. Bethesda No. 25',
    parentAddressVillage: 'Sario',
    parentAddressDistrict: 'Sario',
    parentAddressCity: 'Manado',
    parentAddressProvince: 'Sulawesi Utara',
    phone: '085240112233',
    attendanceSakit: 0,
    attendanceIzin: 0,
    attendanceAlpa: 0,
    ekskul1Name: 'Pramuka',
    ekskul1Grade: 'Sangat Berkembang',
    ekskul1Desc: 'Sangat aktif, berjiwa pemimpin, dan terampil mengoordinasikan tim.',
    teacherNotes: 'Elvira sangat fasih berkomunikasi, berdaya nalar kritis, dan berprestasi merata di seluruh mapel.',
    decision: 'Naik Kelas',
    decisionTargetClass: 'VIII-A',
  },
  {
    id: 'std-7',
    noUrut: 7,
    nis: '232407007',
    nisn: '0107788990',
    name: 'Fadhil Muhammad Nur',
    gender: 'L',
    birthPlace: 'Gorontalo',
    birthDate: '2011-01-18',
    religion: 'Islam',
    prevSchool: 'SD Negeri 01 Manado',
    studentAddress: 'Jl. Diponegoro No. 71, Manado',
    parentFather: 'Nurul Huda',
    parentMother: 'Aisyah Abdullah',
    jobFather: 'Dosen',
    jobMother: 'Guru',
    parentAddressRoad: 'Jl. Diponegoro No. 71',
    parentAddressVillage: 'Mahakeret',
    parentAddressDistrict: 'Wenang',
    parentAddressCity: 'Manado',
    parentAddressProvince: 'Sulawesi Utara',
    phone: '081355667788',
    attendanceSakit: 0,
    attendanceIzin: 1,
    attendanceAlpa: 0,
    ekskul1Name: 'Pramuka',
    ekskul1Grade: 'Berkembang',
    ekskul1Desc: 'Memahami makna Dasa Darma dan mampu mempraktikkannya.',
    teacherNotes: 'Fadhil memiliki pemahaman logika yang baik. Tingkatkan rasa percaya diri dalam presentasi lisan.',
    decision: 'Naik Kelas',
    decisionTargetClass: 'VIII-A',
  },
  {
    id: 'std-8',
    noUrut: 8,
    nis: '232407008',
    nisn: '0108899001',
    name: 'Gabriel Joshua Tumbelaka',
    gender: 'L',
    birthPlace: 'Manado',
    birthDate: '2011-11-10',
    religion: 'Kristen',
    prevSchool: 'SD Kristen Petra Manado',
    studentAddress: 'Jl. 17 Agustus No. 49, Manado',
    parentFather: 'Denny Tumbelaka',
    parentMother: 'Juliana Sompotan',
    jobFather: 'Manajer Perbankan',
    jobMother: 'Notaris',
    parentAddressRoad: 'Jl. 17 Agustus No. 49',
    parentAddressVillage: 'Teling Atas',
    parentAddressDistrict: 'Wanea',
    parentAddressCity: 'Manado',
    parentAddressProvince: 'Sulawesi Utara',
    phone: '081277889900',
    attendanceSakit: 0,
    attendanceIzin: 0,
    attendanceAlpa: 0,
    ekskul1Name: 'Pramuka',
    ekskul1Grade: 'Sangat Berkembang',
    ekskul1Desc: 'Mampu menerapkan kepemimpinan demokratis dan dedikasi tinggi pada regu.',
    ekskul2Name: 'Klub Robotika & Coding',
    ekskul2Grade: 'Sangat Berkembang',
    ekskul2Desc: 'Mampu merakit robot line-follower dan membuat algoritma pemrograman visual.',
    teacherNotes: 'Gabriel memiliki kecerdasan logika dan daya kreativitas tinggi di bidang teknologi.',
    decision: 'Naik Kelas',
    decisionTargetClass: 'VIII-A',
  },
  {
    id: 'std-9',
    noUrut: 9,
    nis: '232407009',
    nisn: '0110011223',
    name: 'Gisella Valerie Lengkong',
    gender: 'P',
    birthPlace: 'Manado',
    birthDate: '2011-07-28',
    religion: 'Kristen',
    prevSchool: 'SD Negeri 11 Manado',
    studentAddress: 'Jl. Ahmad Yani No. 15, Manado',
    parentFather: 'Victor Lengkong',
    parentMother: 'Debora Kaunang',
    jobFather: 'Wiraswasta',
    jobMother: 'PNS',
    parentAddressRoad: 'Jl. Ahmad Yani No. 15',
    parentAddressVillage: 'Sario Kotabaru',
    parentAddressDistrict: 'Sario',
    parentAddressCity: 'Manado',
    parentAddressProvince: 'Sulawesi Utara',
    phone: '081311223344',
    attendanceSakit: 0,
    attendanceIzin: 0,
    attendanceAlpa: 0,
    ekskul1Name: 'Pramuka',
    ekskul1Grade: 'Berkembang',
    ekskul1Desc: 'Cekatan, rapi dalam administrasi regu dan aktif berkegiatan.',
    teacherNotes: 'Gisella adalah siswi yang santun, tekun, dan selalu menjaga kebersihan kelas.',
    decision: 'Naik Kelas',
    decisionTargetClass: 'VIII-A',
  },
  {
    id: 'std-10',
    noUrut: 10,
    nis: '232407010',
    nisn: '0101122334',
    name: 'Helena Kezia Supit',
    gender: 'P',
    birthPlace: 'Manado',
    birthDate: '2011-02-17',
    religion: 'Kristen',
    prevSchool: 'SD GMIM 01 Manado',
    studentAddress: 'Jl. Wolter Monginsidi No. 62, Manado',
    parentFather: 'Jeffrey Supit',
    parentMother: 'Marlina Tambajong',
    jobFather: 'Arsitek',
    jobMother: 'Desainer Grafis',
    parentAddressRoad: 'Jl. Wolter Monginsidi No. 62',
    parentAddressVillage: 'Malalayang Satu',
    parentAddressDistrict: 'Malalayang',
    parentAddressCity: 'Manado',
    parentAddressProvince: 'Sulawesi Utara',
    phone: '081288776655',
    attendanceSakit: 0,
    attendanceIzin: 0,
    attendanceAlpa: 0,
    ekskul1Name: 'Pramuka',
    ekskul1Grade: 'Sangat Berkembang',
    ekskul1Desc: 'Sangat terampil dalam sandi morse, semaphore, serta pertolongan pertama.',
    ekskul2Name: 'Sanggar Seni Tari Tradisional',
    ekskul2Grade: 'Sangat Berkembang',
    ekskul2Desc: 'Sangat luwes membawakan tarian Maengket dan Tari Katrili.',
    teacherNotes: 'Bintang kelas dengan nilai rata-rata tertinggi (Peringkat 1). Pertahankan prestasi membanggakan ini!',
    decision: 'Naik Kelas',
    decisionTargetClass: 'VIII-A',
  },
  {
    id: 'std-11',
    noUrut: 11,
    nis: '232407011',
    nisn: '0102233445',
    name: 'Ivan Christian Mogot',
    gender: 'L',
    birthPlace: 'Bitung',
    birthDate: '2011-10-03',
    religion: 'Kristen',
    prevSchool: 'SD Negeri 02 Bitung',
    studentAddress: 'Jl. Yos Sudarso No. 7, Manado',
    parentFather: 'Frans Mogot',
    parentMother: 'Rita Tangkudung',
    jobFather: 'Pelaut',
    jobMother: 'Ibu Rumah Tangga',
    parentAddressRoad: 'Jl. Yos Sudarso No. 7',
    parentAddressVillage: 'Paal Dua',
    parentAddressDistrict: 'Paal Dua',
    parentAddressCity: 'Manado',
    parentAddressProvince: 'Sulawesi Utara',
    phone: '081233445566',
    attendanceSakit: 0,
    attendanceIzin: 2,
    attendanceAlpa: 0,
    ekskul1Name: 'Pramuka',
    ekskul1Grade: 'Berkembang',
    ekskul1Desc: 'Mampu bekerja sama dengan rekan satu regu dengan solid.',
    teacherNotes: 'Ivan memiliki kemauan belajar yang baik. Terus tingkatkan ketelitian dalam pengerjaan soal hitungan.',
    decision: 'Naik Kelas',
    decisionTargetClass: 'VIII-A',
  },
  {
    id: 'std-12',
    noUrut: 12,
    nis: '232407012',
    nisn: '0113344556',
    name: 'Jessica Aurelia Rotinsulu',
    gender: 'P',
    birthPlace: 'Manado',
    birthDate: '2011-12-25',
    religion: 'Kristen',
    prevSchool: 'SD Katolik 02 Manado',
    studentAddress: 'Jl. Martadinata No. 51, Manado',
    parentFather: 'Royke Rotinsulu',
    parentMother: 'Diana Warouw',
    jobFather: 'Wiraswasta',
    jobMother: 'Karyawan Swasta',
    parentAddressRoad: 'Jl. Martadinata No. 51',
    parentAddressVillage: 'Dendengan Luar',
    parentAddressDistrict: 'Tikala',
    parentAddressCity: 'Manado',
    parentAddressProvince: 'Sulawesi Utara',
    phone: '081344998877',
    attendanceSakit: 0,
    attendanceIzin: 0,
    attendanceAlpa: 0,
    ekskul1Name: 'Pramuka',
    ekskul1Grade: 'Sangat Berkembang',
    ekskul1Desc: 'Aktif menyuarakan ide kreatif dan membantu teman yang mengalami kendala.',
    teacherNotes: 'Jessica sangat tekun, bertanggung jawab dalam tugas sekolah, dan disenangi teman-temannya.',
    decision: 'Naik Kelas',
    decisionTargetClass: 'VIII-A',
  }
];

// Sample Formatif Assessment Matrix (studentId -> subjectId -> scores)
export const initialSampleFormatifData: Record<string, Record<string, Record<number, number>>> = {
  'std-1': {
    agama: { 1: 100, 2: 100, 3: 100, 4: 100, 5: 100 },
    pancasila: { 1: 85, 2: 82, 3: 88, 4: 89, 5: 85 },
    bindonesia: { 1: 85, 2: 82, 3: 88, 4: 89, 5: 85 },
    matematika: { 1: 85, 2: 82, 3: 88, 4: 89, 5: 85 },
    ipa: { 1: 85, 2: 82, 3: 88, 4: 89, 5: 85 },
    ips: { 1: 85, 2: 82, 3: 88, 4: 89, 5: 85 },
    binggris: { 1: 85, 2: 82, 3: 88, 4: 89, 5: 85 },
    pjok: { 1: 85, 2: 82, 3: 88, 4: 89, 5: 85 },
    seni: { 1: 85, 2: 82, 3: 88, 4: 89, 5: 85 },
    informatika: { 1: 85, 2: 82, 3: 88, 4: 89, 5: 85, 6: 90, 7: 80, 8: 95, 9: 85, 10: 88, 11: 88, 12: 90 },
  },
  'std-2': {
    agama: { 1: 81, 2: 84, 3: 87, 4: 90, 5: 87 },
    pancasila: { 1: 95, 2: 94, 3: 90, 4: 95, 5: 93 },
    bindonesia: { 1: 95, 2: 94, 3: 90, 4: 95, 5: 93 },
    matematika: { 1: 95, 2: 94, 3: 90, 4: 95, 5: 93 },
    ipa: { 1: 95, 2: 94, 3: 90, 4: 95, 5: 93 },
    ips: { 1: 95, 2: 94, 3: 90, 4: 95, 5: 93 },
    binggris: { 1: 95, 2: 94, 3: 90, 4: 95, 5: 93 },
    pjok: { 1: 95, 2: 94, 3: 90, 4: 95, 5: 93 },
    seni: { 1: 95, 2: 94, 3: 90, 4: 95, 5: 93 },
    informatika: { 1: 95, 2: 94, 3: 90, 4: 95, 5: 93, 6: 90, 7: 90, 8: 90, 9: 88, 10: 90, 11: 92, 12: 94 },
  },
  'std-3': {
    agama: { 1: 81, 2: 84, 3: 87, 4: 85, 5: 87 },
    pancasila: { 1: 81, 2: 84, 3: 87, 4: 85, 5: 87 },
    bindonesia: { 1: 81, 2: 84, 3: 87, 4: 85, 5: 87 },
    matematika: { 1: 81, 2: 84, 3: 87, 4: 85, 5: 87 },
    ipa: { 1: 81, 2: 84, 3: 87, 4: 85, 5: 87 },
    ips: { 1: 81, 2: 84, 3: 87, 4: 85, 5: 87 },
    binggris: { 1: 81, 2: 84, 3: 87, 4: 85, 5: 87 },
    pjok: { 1: 81, 2: 84, 3: 87, 4: 85, 5: 87 },
    seni: { 1: 81, 2: 84, 3: 87, 4: 85, 5: 87 },
    informatika: { 1: 81, 2: 84, 3: 87, 4: 85, 5: 87, 6: 90, 7: 90, 8: 95, 9: 87, 10: 80, 11: 90, 12: 85 },
  },
  'std-10': {
    agama: { 1: 95, 2: 98, 3: 95, 4: 96, 5: 94 },
    pancasila: { 1: 95, 2: 98, 3: 95, 4: 96, 5: 94 },
    bindonesia: { 1: 95, 2: 98, 3: 95, 4: 96, 5: 94 },
    matematika: { 1: 95, 2: 98, 3: 95, 4: 96, 5: 94 },
    ipa: { 1: 95, 2: 98, 3: 95, 4: 96, 5: 94 },
    ips: { 1: 95, 2: 98, 3: 95, 4: 96, 5: 94 },
    binggris: { 1: 95, 2: 98, 3: 95, 4: 96, 5: 94 },
    pjok: { 1: 95, 2: 98, 3: 95, 4: 96, 5: 94 },
    seni: { 1: 95, 2: 98, 3: 95, 4: 96, 5: 94 },
    informatika: { 1: 95, 2: 98, 3: 95, 4: 96, 5: 94, 6: 95, 7: 98, 8: 95, 9: 96, 10: 94, 11: 98, 12: 95 },
  }
};

// Sample Sumatif Assessment Matrix
export const initialSampleSumatifData: Record<string, Record<string, { lm: Record<number, { tes: number, nonTes: number }>, sasTes: number, sasNonTes: number }>> = {
  'std-1': {
    agama: { lm: { 1: { tes: 80, nonTes: 90 } }, sasTes: 90, sasNonTes: 90 },
    pancasila: { lm: { 1: { tes: 85, nonTes: 85 } }, sasTes: 85, sasNonTes: 85 },
    bindonesia: { lm: { 1: { tes: 85, nonTes: 85 } }, sasTes: 85, sasNonTes: 85 },
    matematika: { lm: { 1: { tes: 85, nonTes: 85 } }, sasTes: 85, sasNonTes: 85 },
    ipa: { lm: { 1: { tes: 85, nonTes: 85 } }, sasTes: 85, sasNonTes: 85 },
    ips: { lm: { 1: { tes: 85, nonTes: 85 } }, sasTes: 85, sasNonTes: 85 },
    binggris: { lm: { 1: { tes: 85, nonTes: 85 } }, sasTes: 85, sasNonTes: 85 },
    pjok: { lm: { 1: { tes: 85, nonTes: 85 } }, sasTes: 85, sasNonTes: 85 },
    seni: { lm: { 1: { tes: 85, nonTes: 85 } }, sasTes: 85, sasNonTes: 85 },
    informatika: { lm: { 1: { tes: 85, nonTes: 85 } }, sasTes: 85, sasNonTes: 85 },
  },
  'std-2': {
    agama: { lm: { 1: { tes: 90, nonTes: 89 } }, sasTes: 89, sasNonTes: 89 },
    pancasila: { lm: { 1: { tes: 95, nonTes: 95 } }, sasTes: 95, sasNonTes: 95 },
    bindonesia: { lm: { 1: { tes: 95, nonTes: 95 } }, sasTes: 95, sasNonTes: 95 },
    matematika: { lm: { 1: { tes: 95, nonTes: 95 } }, sasTes: 95, sasNonTes: 95 },
    ipa: { lm: { 1: { tes: 95, nonTes: 95 } }, sasTes: 95, sasNonTes: 95 },
    ips: { lm: { 1: { tes: 95, nonTes: 95 } }, sasTes: 95, sasNonTes: 95 },
    binggris: { lm: { 1: { tes: 95, nonTes: 95 } }, sasTes: 95, sasNonTes: 95 },
    pjok: { lm: { 1: { tes: 95, nonTes: 95 } }, sasTes: 95, sasNonTes: 95 },
    seni: { lm: { 1: { tes: 95, nonTes: 95 } }, sasTes: 95, sasNonTes: 95 },
    informatika: { lm: { 1: { tes: 95, nonTes: 95 } }, sasTes: 95, sasNonTes: 95 },
  }
};
